### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by simonefuoco** [simonefuoco/tappy#2]
Add a .gitignore file to prevent pushing unwanted file to remote repository.

**Comment by whattrash** [comment]
Got this one!

**Comment by simonefuoco** [comment]
Hi @whattrash, thank you for pushing your pull request. But the related pull request seems to be a very generic .gitignore file (contain ignore for python files for example) that do not respect the scope of this project.
I'm sorry but I'm setting up the project so there are no much information about it (I have started only today).
The fix is already done. (see - 182c64e)
As soon as possible I add a contribute file to this project and a proper description.
So if you can contribute, you are welcome.
For example see #1 
Excuse me and thank yout.
